config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get '/', to: 'opportunities#home', as: 'home'

  get '/opportunities/approvals', to: 'opportunities#approvals', as: 'approvals'

  get '/opportunities/:id/publish', to: 'opportunities#publish', as: 'publish'

  get '/opportunities/:id/unpublish', to: 'opportunities#unpublish', as: 'unpublish'

  resources :opportunities

end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  belongs_to :user
  has_many :opportunity_tags
  has_many :tags, through: :opportunity_tags
  has_attached_file :pic, default_url: ""

  validates_attachment :pic, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]}
  validates :title, :description, :opportunity_type, :startdate, :duration, :location,  presence: true
  validates :title, :uniqueness => true


  def self.search(search)
    s = "%#{search}%"
    Opportunity.where("title LIKE ? or description LIKE ? or location LIKE ?", s, s, s)
  end
  # def self.search(search)
  #   @s = "%#{search}%"
  #   @user = User.find_by("name LIKE ?", @s)
  #   where("title LIKE ? or description LIKE ? or user_id = ?", @s, @s, @user.id)
  # end
  # def self.search(search)
  #   s = "%#{search}%"
  #
  #   Opportunity.joins(:user).where("users.name LIKE ?", s)
  # end

  # def self.search(search)
  #   s = "%#{search}%"
  #   titles_and_descriptons = Opportunity.where("title LIKE ? or description LIKE ?", s, s)
  #   organizations = Opportunity.joins(:user).where("users.name LIKE ?", s)
  #   titles_and_descriptons + organizations
  # end

  # def self.search(search)
  #   s = "%#{search}%"
  #   Opportunity.where("title LIKE ? or description LIKE ?", s, s).or.joins(:user).where("users.name LIKE ?", s)
  # end
end

app/models/opportunity_tag.rb
class OpportunityTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :opportunity
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :opportunity_tags
  has_many :opportunities, through: :opportunity_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :opportunities
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end

end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController

  def home
    published_opportunities = Opportunity.where published: true
    if params[:search]
      print_opportunities = published_opportunities.search(params[:search])
    else
      print_opportunities = published_opportunities
    end
    @opportunities= print_opportunities.order(startdate: :asc)
  end

  def show
    @opportunity = Opportunity.find_by id: params[:id]
    @tags = @opportunity.tags
  end

  def index
    if current_user.role == "Curator"
      opportunities = Opportunity.all
    else
      opportunities = current_user.opportunities
    end
    opportunities_in_order = opportunities.order(startdate: :asc)
    @not_published_yet = opportunities_in_order.where published: false
    @published = opportunities_in_order.where published: true
  end

  def new
    @opportunity = Opportunity.new
  end

  def create
    @opportunity = current_user.opportunities.new(opportunity_params)

    if @opportunity.save
      redirect_to @opportunity, :notice => "Your opportunity was created"
    else
      render "new"
     end
  end

  def destroy
    if current_user.role == "Curator"
      @opportunity = Opportunity.find_by id: params[:id]
    else
      @opportunity = current_user.opportunities.find_by id: params[:id]
    end
    @opportunity.delete

    redirect_to opportunities_path, :notice => "Your opportunity was deleted"
  end

  def edit
    if current_user.role == "Curator"
      @opportunity = Opportunity.find(params[:id])
    else
      @opportunity = current_user.opportunities.find(params[:id])
    end
  end

  def update
    if current_user.role == "Curator"
      @opportunity = Opportunity.find(params[:id])
    else
      @opportunity = current_user.opportunities.find(params[:id])
    end
    if @opportunity.published == false
      @opportunity.update!(opportunity_params)
    end
    redirect_to opportunities_path
  end

  def approvals
    opportunities = Opportunity.where published: false
    @opportunities = opportunities.order(created_at: :desc)
  end

  def publish
    if current_user.role == "Curator"
      @opportunity = Opportunity.find_by id: params[:id]
      @opportunity.update(:published => true)
    end

    redirect_to opportunities_path
  end

  def unpublish
    @opportunity = Opportunity.find_by id: params[:id]
    @opportunity.update(:published => false)

    redirect_to opportunities_path
  end

  private
  def opportunity_params
    params.require(:opportunity).permit(:title, :description, :opportunity_type, :startdate, :duration, :location, :pic)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show



end

app/helpers/application_helper.rb
module ApplicationHelper
  def sign_in_hide
    unless user_signed_in?
      raw("style='display: none;'")
    end
  end
  def log_out_hide
    if user_signed_in?
      raw("style='display: none;'")
    end
  end
  def if_current_user_name
    if user_signed_in?
      current_user.name
    end
  end
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Univercity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%=params[:controller]%> <%=params[:action]%>">
  <nav class="navbar navbar-default navabar-header">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand"><span class="black_span">Univer</span><span class="color_span">City/</span></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Find Opportunity", home_path %></li>
          <li><%= link_to "Create Opportunity", new_opportunity_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <%unless user_signed_in?%>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
          <%if user_signed_in?%>
            <%if current_user.role == "Curator";%><li class="active"><a href="#"><span class="glyphicon glyphicon-sunglasses" aria-hidden="true"></span> Curator <span class="sr-only">(current)</span></a></li><% end %>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= if_current_user_name %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "My Opportunities", opportunities_path %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                </ul>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <%if params[:action] == "home" %>
    <div class="home_background">
      <div class="jumbotron jumbotron_home">
        <div class="container container_home">
          <h1>&nbspUniver<span class="color_span">City/</span></h1>
          <p><span class="home-text">&nbspCitizens that learn/&nbsp</span></p>
          <div class="home-text"><p>&nbspLook for courses, workshops and events in Barcelona/&nbsp</p></div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-info" role="alert">
        <p><%= value %></p>
      </div>
    <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/opportunities/edit.html.erb
<div class="container">
  <% if user_signed_in? %>
    <% if @opportunity.published == false %>

      <%= render partial: "partials/form", locals: {title: "Edit Oportunity", path_variable: opportunity_path, submit_variable: "Save changes"} %>

    <% else %>
    <div class="panel-signin">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2>Opportunity must be unpublished first in order to get edited</h2>
        </div>
      </div>
    </div>
    <% end %>
  <% else %>
    <div class="panel-signin">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2>Nobody logged in</h2>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/opportunities/home.html.erb
<div class="container">
  <nav class="navbar navbar-default home-navbar">
    <div class="container-fluid">
      <%= form_tag(home_path, :method => "get", id: "search-form", class: "navbar-form navbar-left") do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Search opportunities", class:"form-control" %>
        </div>
        <%= submit_tag "Search", class: "btn btn-info" %>
      <% end %>
    </div>
  </nav>

    <% if @opportunities.present? %>

      <%= render "partials/opportunities_thumbnails" %>

    <% else %>
      <% if params[:search] %>
        <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
      <% end %>
    <% end %>

</div>

app/views/opportunities/index.html.erb
<div class="container">
  <% if user_signed_in? %>
    <h2 class="my_opportunities">Welcome <%= current_user.name %>!</h2>
    <h2>My Opportunities</h2>
    <%= link_to 'Create Opportunity', new_opportunity_path, class: 'btn btn-info', role: 'button' %>
    <br>
    <% if @not_published_yet.length > 0 %>
      <h3>Not published yet (Waiting for approval)</h3>

      <%= render partial: "partials/opportunities_index", locals: {opportunities: @not_published_yet, button: "publish"}%>

    <% end %>
    <br>
    <% if @published.length > 0 %>
      <h3>Published</h3>

      <%= render partial: "partials/opportunities_index", locals: {opportunities: @published, button: "unpublish"}%>

    <% end %>
    <br>
  <% else %>
    <h2>Nobody logged in</h2>
  <% end %>
</div>

app/views/opportunities/new.html.erb
<div class="container">
  <% if user_signed_in? %>

    <%= render partial: "partials/form", locals: {title: "Create Oportunity", path_variable: opportunities_path, submit_variable: "Create Opportunity"} %>

  <% else %>
    <div class="panel-signin">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2>Create opportunity</h2>
        </div>
        <div class="panel-body">
          <h4>In order to publish new opportunities you have to Log in or Sign up: </h4>
          <h4><%= link_to 'Log in', new_user_session_path, class: 'btn btn-info', role: 'button' %> <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-info', role: 'button' %></h4>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/opportunities/show.html.erb
<div class="container">

  <div class="background_show" style="background-image: url(<%= @opportunity.pic.url %>);">
    <div class="jumbotron jumbotron_show">
      <h4><%= @opportunity.startdate.strftime("%d / %B") %></h4>
      <h1><%= @opportunity.title %></h1>
      <p><%= @opportunity.opportunity_type %></p>
    </div>
  </div>
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-body">
      <p><strong>Description: </strong><%= @opportunity.description %></p>
    </div>

    <!-- List group -->
    <ul class="list-group">
      <li class="list-group-item"><strong>Organization: </strong><%= @opportunity.user.name %></li>
      <li class="list-group-item"><strong>Duration: </strong><%= @opportunity.duration %></li>
      <li class="list-group-item"><strong>Location: </strong><%= @opportunity.location %></li>
    </ul>
    <div class="panel-footer">
      <strong>Tags: </strong>
        <% @tags.each { |tag| %>
          <span class="label label-info"> <%= tag.name %></span> <%=" "%>
        <% } %>
    </div>

  </div>
  <!-- <img src="http://www.planwallpaper.com/static/images/Download-Cool-Wallpaper-Cars-Background.jpg" alt="opportunity picture" class="img-rounded opportunity_picture"> -->
</div>

app/views/partials/_form.html.erb
<div class="panel-signin">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2><%= title %></h2>
    </div>
    <div class="panel-body">
      <% if @opportunity.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <h4><strong>Errors:</strong></h4>
            <ul>
              <% @opportunity.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        </div>
      <% end %>
      <br />
      <%= form_for @opportunity, url: path_variable do |f| %>
        <div class="field form-group">
          <%= f.label :title %><br />
          <%= f.text_field :title, autofocus: true, :class => "form-control" %>
        </div>
        <div class="field form-group">
          <%= f.label :description %><br />
          <%= f.text_field :description, :class => "form-control" %>
        </div>
        <div class="field form-group">
          <%= f.label :opportunity_type %><br />
          <%= f.select(:opportunity_type, ['Event', 'Workshop', 'Course'], {}, { :class => 'form-control' }) %>
        </div>
        <div class="field form-group">
          <%= f.label :start_date %><br />
          <%= f.date_field :startdate, :class => "form-control" %>
        </div>
        <div class="field form-group">
          <%= f.label :duration %><br />
          <%= f.text_field :duration, :class => "form-control" %>
        </div>
        <div class="field form-group">
          <%= f.label :location %><br />
          <%= f.text_field :location, :class => "form-control" %>
        </div>
        <div class="field form-group">
          <%= f.label :opportnity_picture %>
          <%= f.file_field :pic %>
        </div>
        <div class="actions">
          <%= f.submit submit_variable, :class => "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/partials/_opportunities.html.erb
<ul class="media-list">
  <% @opportunities.each { |opportunity| %>

    <li class="media">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="media-left">
            <%= link_to(opportunity_path(opportunity.id)) do %>
              <% if opportunity.pic.url != "" %>
                <%= image_tag(opportunity.pic.url, class: "media-object") %>
              <% else %>
                <%= image_tag("opportunity_default.jpg", class: "media-object") %>
              <% end %>
            <% end %>
          </div>
          <div class="media-body">
            <h5><%= opportunity.startdate.strftime("%d / %B")  %></h5>
            <%= link_to(opportunity_path(opportunity.id)) do %>
              <h4 class="media-heading"><%= opportunity.title %></h4>
            <% end %>
            <h6> by <%= opportunity.user.name %></h6>
            <%= opportunity.opportunity_type %>
          </div>
        </div>
        <div class="panel-footer">
        </div>
      </div>
    </li>
    
  <% } %>
</ul>

app/views/partials/_opportunities_index.html.erb
<ul class="media-list">
  <% opportunities.each { |opportunity| %>

    <li class="media">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="media-left">
            <%= link_to(opportunity_path(opportunity.id)) do %>
              <% if opportunity.pic.url != "" %>
                <%= image_tag(opportunity.pic.url, class: "media-object") %>
              <% else %>
                <%= image_tag("opportunity_default.jpg", class: "media-object") %>
              <% end %>
            <% end %>
          </div>
          <div class="media-body">
            <h5><%= opportunity.startdate.strftime("%d / %B")  %></h5>
            <%= link_to(opportunity_path(opportunity.id)) do %>
              <h4 class="media-heading"><%= opportunity.title %></h4>
            <% end %>
            <%= opportunity.opportunity_type %>
            <h6> by <%= opportunity.user.name %></h6>
          </div>
        </div>
        <div class="panel-footer">
          <%if button == "publish"%>
            <%if current_user.role == "Curator";%><%= link_to "Publish", publish_path(opportunity.id), class: "btn btn-success" %><% end %>
          <%elsif button == "unpublish"%>
            <%= link_to "Unpublish", unpublish_path(opportunity.id), class: "btn btn-warning" %>
          <% end %>
          <%= link_to "Edit", edit_opportunity_path(opportunity.id), class: "btn btn-warning" %>
          <%= link_to "Delete", opportunity_path(opportunity.id), :method => "DELETE", class: "btn btn-danger" %>
        </div>
      </div>
    </li>
  <% } %>
</ul>

app/views/partials/_opportunities_thumbnails.html.erb
<div class="row">
    <% @opportunities.each { |opportunity| %>

        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <%= link_to(opportunity_path(opportunity.id)) do %>
              <% if opportunity.pic.url != "" %>
                <div class="opportunity-background" style="background-image: url(<%= opportunity.pic.url %>);"></div>
              <% else %>
                <div class="opportunity-background background-image-default"></div>
              <% end %>
            <% end %>
            <div class="caption">
              <h5><%= opportunity.startdate.strftime("%d / %B")  %></h5>
              <%= link_to(opportunity_path(opportunity.id)) do %>
                <h4 class="media-heading"><%= opportunity.title %></h4>
              <% end %>
              <%= opportunity.opportunity_type %>
              <h6> by <%= opportunity.user.name %></h6>
            </div>
          </div>
        </div>

    <% } %>
</div>

app/views/partials/_opportunities_thumbnails2.html.erb
<div class="row">
    <% @opportunities.each { |opportunity| %>

        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <%= link_to(opportunity_path(opportunity.id)) do %>
              <% if opportunity.pic.url != "" %>
                <%= image_tag(opportunity.pic.url, class: "opportunity-image") %>
              <% else %>
                <%= image_tag("opportunity_default.jpg", class: "opportunity-image") %>
              <% end %>
            <% end %>
            <div class="caption">
              <h5><%= opportunity.startdate.strftime("%d / %B")  %></h5>
              <%= link_to(opportunity_path(opportunity.id)) do %>
                <h4 class="media-heading"><%= opportunity.title %></h4>
              <% end %>
              <h6> by <%= opportunity.user.name %></h6>
              <%= opportunity.opportunity_type %>
            </div>
          </div>
        </div>

    <% } %>
</div>

app/views/users/show.html.erb
<div class="container">
  <% if user_signed_in? %>
    <h2>Welcome <%= current_user.name %>!</h2>
    <%= link_to 'Create new opportunity', users_create_path, class: 'btn btn-primary', role: 'button' %>
    <br>
    <br>
    <ul class="media-list">
      <% @opportunities.each { |opportunity| %>

        <li class="media">
          <div class="media-left">
            <%= link_to(opportunity_path(opportunity.id)) do %>
              <img class="media-object" src="http://static1.squarespace.com/static/565241a5e4b085e3bb8d651c/t/5675f84357eb8de4eb35abf5/1450571844210/workshop+2.jpg?format=1500w" alt="workshop full of people">
            <% end %>
          </div>
          <div class="media-body">
            <h5><%= opportunity.startdate.strftime("%d / %B")  %></h5>
            <%= link_to(opportunity_path(opportunity.id)) do %>
              <h4 class="media-heading"><%= opportunity.title %></h4>
            <% end %>
            <h6> by <%= opportunity.organization %></h6>
            <%= opportunity.opportunity_type %>
          </div>
        </li>

      <% } %>
      <br>
      <%= link_to 'Logout', destroy_user_session_path, method: 'DELETE' %>
    <% else %>
      <h2>Nobody logged in</h2>
    <% end %>
  </ul>
</div>